### ISSUE TITLE
unable to handle empty string

### ISSUE THREAD

**Issue by bmeck** [CSSLint/parser-lib#210] opened 2016-04-11 15:23 UTC
```js
    var parserlib = require('parserlib');
    var parser = new parserlib.css.Parser();
    parser.parse('');
```

```log
TypeError: Cannot read property 'getLine' of null
    at TokenStreamBase.mix._getToken (/Users/bfarias/Documents/html-dependencies/node_modules/parserlib/lib/node-parserlib.js:4737:33)
    at TokenStreamBase.get (/Users/bfarias/Documents/html-dependencies/node_modules/parserlib/lib/node-parserlib.js:726:22)
    at TokenStreamBase.match (/Users/bfarias/Documents/html-dependencies/node_modules/parserlib/lib/node-parserlib.js:620:24)
    at Parser.additions._charset (/Users/bfarias/Documents/html-dependencies/node_modules/parserlib/lib/node-parserlib.js:1445:33)
    at Parser.additions._stylesheet (/Users/bfarias/Documents/html-dependencies/node_modules/parserlib/lib/node-parserlib.js:1313:22)
    at Parser.additions.parse (/Users/bfarias/Documents/html-dependencies/node_modules/parserlib/lib/node-parserlib.js:3398:22)
    at [stdin]:3:12
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (module.js:409:26)
```

**Comment by ideadapt** [comment] 2016-05-24 18:57
duplicate of https://github.com/CSSLint/parser-lib/pull/183

**Closed** 2016-07-27 06:40 UTC
